@baseUrl = https://nacao-aprovada-back-production.up.railway.app

###
# Create rooms
# @name createRoom
POST {{baseUrl}}/courses/create
Accept: application/json
Content-Type: application/json

{
    "institution": "Instituto Federal de São Paulo",
    "jobPosition": "Professor"
}

###

POST {{baseUrl}}/register-user
Accept: application/json
Content-Type: application/json

{
  "name": "Matteus varlesse",
  "email": "matteus.varlesse@genesis-dataculture.com",
  "cpf": "48699028857",
  "phone": "+55 12 91234-5678",
  "role": "student",
  "preferedStartDate": "2024-06-01",
  "studyAvailability": {
    "monday": 120,
    "tuesday": 90,
    "wednesday": 60,
    "thursday": 30,
    "friday": 0,
    "saturday": 0,
    "sunday": 0
  },
  "courses": [
    {
      "id": "ca4cf3aa-d713-496c-9d88-4b0722a17d11",
      "registrationDate": "2024-06-01",
      "expirationDate": "2025-06-01"
    }
  ]
}
